### PR TITLE
Move the package to a dedicated repo

### PR DESCRIPTION
**Pull request by dimitrisnl**

### CODE REVIEW

**Comment by nazrhom** [comment]
@dimitrisnl since this is the first PR the checks are not required yet, should get setup correctly after a merge to master. We need to wait for the store-github and store-npm checks to appear.

**Review by nazrhom — APPROVED** [review]

**Comment by nazrhom** [comment]
also needs the v1.2.2 tag

**Comment by dimitrisnl** [comment]
@resin-ci retest

**Comment by dimitrisnl** [comment]
@resin-ci retest

**Comment by nazrhom** [comment]
@dimitrisnl the commit is also missing a change-type

**Pull request merged**
